### ISSUE TITLE
Github ActionsでPRがマージされたときに次のイシューを自動的に立てる

### ISSUE THREAD

**Issue by nanae772** [VOICEVOX/voicevox_engine#1564]
## 内容

「このＰＲがマージされたら別のイシューを立てて対応する」ということがよくあると思います。
ですがマージまで期間が空いていたりするとそのことを忘れてしまったり、そもそも上記のことを覚えておかないといけないということ自体が負荷になりそうです。

なので

1. PRの説明文に「これがマージされたら立てるイシューリスト」的なのを書いておく
2. PRがマージされたら、Github Actionsがそれを読み取って自動的にイシューを立てる

みたいなのができると便利そうです（イシューの予約投稿というイメージ）。

### Pros 良くなる点
1.  イシューの立て忘れが無くなる
2. 覚えておかなければならないことが減る

### Cons 悪くなる点
1. PR作成者の悪意によってイシューが大量に作られたりするかも
    1. 立てられるイシューの上限は決めておく必要がありそう

### 実現方法

ChatGPTに聞いたら、以下のような感じでやればよさそうと教えてくれました。

下をPRの説明文に書いておく
```md
<!-- issue-list-start -->
- 新機能のテスト
- ドキュメントの更新
- バグ修正のフォローアップ
<!-- issue-list-end -->
```

以下のワークフローファイルを作成する
```yaml
name: Create Issues on PR Merge

on:
  pull_request:
    types:
      - closed  # PRが閉じられた（マージまたはクローズされた）とき

jobs:
  create_issues:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'create-issue-on-merge')
    runs-on: ubuntu-latest

    steps:
      - name: Extract Issue Titles
        id: extract
        run: |
          ISSUE_TITLES=$(echo "${{ github.event.pull_request.body }}" | sed -n '/<!-- issue-list-start -->/,/<!-- issue-list-end -->/p' | sed '1d;$d' | sed 's/^- //g' | tr '\n' ',' | sed 's/,$//')
          echo "ISSUE_TITLES=$ISSUE_TITLES" >> $GITHUB_ENV

      - name: Create Issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitles = process.env.ISSUE_TITLES.split(',');
            for (const title of issueTitles) {
              if (title.trim() === "") continue; // 空のタイトルをスキップ
              
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title.trim(),
                body: `This issue was automatically created because PR #${{ github.event.pull_request.number }} was merged.\n\nPlease add the necessary details.`
              });
            }
```

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

とりあえず最近活動しているvoicevox_engineに立てましたが、1個できたら他のリポジトリでも流用できそうです。
