### ISSUE TITLE
カバレッジ取得サービスを見直す

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox_engine#1573]
## 内容
coveralls が落ちて、[CIがコケる](https://github.com/VOICEVOX/voicevox_engine/actions/runs/14154449039/job/39651876655)ことがある。
取れる選択肢としては、
- coveralls をやめて、codecov を使う
- coveralls をやめる。ほかツールは使わない

### Pros 良くなる点
CI がこけなくなる

### Cons 悪くなる点
古いカバレッジが見れなくなる

### 実現方法
Github Actions の workflow を修正する

**Comment by Hiroshiba** [comment]
coveralls って使ってる方いるんだろうか、というのがちょっと気になってます！
engineによくコミットしてくださる方・実装してくださった方にメンション飛ばしてみます、もし使ってたらコメントいただければ！！
@y-chan @tarepan @takana-v @sevenc-nanashi @sabonerune @nanae772 

あとGithub Workflowは確かそのステップがエラーであっても無視して次に進む機能があった気がします。
一時しのぎですが、それを付けるとかでも良いのかも･･･？

**Comment by sevenc-nanashi** [comment]
coverallsという名前を今初めて知りました...

**Comment by raa0121** [comment]
https://h-miyako.hatenablog.com/entry/2016/02/06/194125
coveralls と codecov を比較してる記事です。
私が知ってるOSS も codecov を採用してるものが多い気がします。

**Comment by nanae772** [comment]
ちょうど一時しのぎ的にtest.ymlを以下のようにしてCIを止めないみたいな解決を（ChatGPTに教えてもらって）やろうかなと思ってましたが、Github Workflow自体にそういう設定があるならそっちのほうがいいかもですね。

```yml
      - name: <Deploy> Submit coverage results to Coveralls
        if: runner.os == 'Linux'
        # Coveralls にアップロード失敗してもCIは継続させる
        run: coveralls --service=github || echo "Coveralls upload failed, but continuing"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

そんなに実装してないので恐縮ですが、テスト書いたあとにcoverallsの数値見て「お～、ちょっと上がってる」みたいなプチ満足感を得たことはありました。

カバレージ率は高ければOKってわけじゃないようですが、低すぎると「テストが足りないのかも？」という指標になりそうなので、カバレージ率が手軽に見られること自体は悪くないと個人的に思いました。

ただ、外部のサービスに依存して関係無いのにCIが止まっちゃうことは避けたほうがよさそうという気持ちです。
